#!/bin/sh


MONITORDIR="/storage/sflowInput"
KEY="qwertyuiopasdfghjklzxcvbnmqwerty" 

/usr/local/bin/inotifywait -m -r -e moved_to --format '%w%f' "${MONITORDIR}" | while read NEWFILE
do
        YEAR=$(date +"%Y")
        MONTH=$(date +"%m")
        DAY=$(date +"%d")
        STAMP=$(date +"%T")
        mkdir -p /storage/sflowOutput/$YEAR/$MONTH/$DAY
	/usr/local/bin/nfanon -r $NEWFILE -w /storage/sflowOutput/$YEAR/$MONTH/$DAY/$STAMP -K $KEY
	echo "* Anonymized: $NEWFILE"
done
